project:
  type: book
  output-dir: docs

book:
  title: "INHERSEED"
  date: last-modified
  chapters:
    - index.qmd
    - 01_GreenhouseExp.qmd
  appendices:
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual